// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: url.sql

package db

import (
	"context"
	"time"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls(
    original_url,
    short_code,
    is_custom,
    expired_at
) VALUES (
    $1,$2,$3,$4
) 
RETURNING id, original_url, short_code, is_custom, expired_at, created_at
`

type CreateUrlParams struct {
	OriginalUrl string    `json:"original_url"`
	ShortCode   string    `json:"short_code"`
	IsCustom    bool      `json:"is_custom"`
	ExpiredAt   time.Time `json:"expired_at"`
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createUrl,
		arg.OriginalUrl,
		arg.ShortCode,
		arg.IsCustom,
		arg.ExpiredAt,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.IsCustom,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUrlByShortCode = `-- name: GetUrlByShortCode :one
SELECT id, original_url, short_code, is_custom, expired_at, created_at
FROM urls
WHERE short_code = $1
`

func (q *Queries) GetUrlByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getUrlByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.IsCustom,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const isShortCodeAvailable = `-- name: IsShortCodeAvailable :one
SELECT NOT EXISTS (
    SELECT 1
    FROM urls
    WHERE short_code = $1
) AS is_available
`

func (q *Queries) IsShortCodeAvailable(ctx context.Context, shortCode string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isShortCodeAvailable, shortCode)
	var is_available bool
	err := row.Scan(&is_available)
	return is_available, err
}

const urlExpiredAt = `-- name: UrlExpiredAt :one
SELECT expired_at
FROM urls
WHERE short_code = $1
`

func (q *Queries) UrlExpiredAt(ctx context.Context, shortCode string) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, urlExpiredAt, shortCode)
	var expired_at time.Time
	err := row.Scan(&expired_at)
	return expired_at, err
}
